ecomapp/urls.py
from django.conf.urls import url
from django.urls import reverse_lazy
from django.contrib.auth.views import LogoutView
from django.views.generic.base import TemplateView

from ecomapp.views import (
	base_view, 
	category_view, 
	product_view, 
	cart_view, 
	add_to_cart_view, 
	remove_from_cart_view, 
	change_item_qty,
	checkout_view,
	order_create_view,
	make_order_view,
	account_view,
	registration_view,
	login_view
	)

urlpatterns = [	
    url(r'^category/(?P<category_slug>[-\w]+)/$', category_view, name='category_detail'),
    url(r'^product/(?P<product_slug>[-\w]+)/$', product_view, name='product_detail'),
    url(r'^add_to_cart/$', add_to_cart_view, name='add_to_cart'),
    url(r'^remove_from_cart/$', remove_from_cart_view, name='remove_from_cart'),
    url(r'^change_item_qty/$', change_item_qty, name='change_item_qty'),
    url(r'^cart/$', cart_view, name='cart'),
    url(r'^checkout/$', checkout_view, name='checkout'),
    url(r'^order/$', order_create_view, name='create_order'),
    url(r'^make_order/$', make_order_view, name='make_order'),
    url(r'^thank_you/$', TemplateView.as_view(template_name='thank_you.html'), name='thank_you'),
    url(r'^account/$', account_view, name='account'),
    url(r'^registration/$', registration_view, name='registration'),
    url(r'^login/$', login_view, name='login'),
    url(r'^logout/$', LogoutView.as_view(next_page=reverse_lazy('base')), name='logout'),
    url(r'^$', base_view, name='base'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('ecomapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomapp/models.py
from decimal import Decimal
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.urls import reverse
from transliterate import translit


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'category_slug': self.slug})


def pre_save_category_slug(sender, instance, *args, **kwargs):
    if not instance.slug:
        slug = slugify(translit(str(instance.name), reversed=True))
        instance.slug = slug


pre_save.connect(pre_save_category_slug, sender=Category)


class Brand(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


def image_folder(instance, filename):
    filename = instance.slug + '.' + filename.split('.')[1]
    return "{0}/{1}".format(instance.slug, filename)


class ProductManager(models.Manager):
    def all(self, *args, **kwargs):
        return super(ProductManager, self).get_queryset().filter(available=True)


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    brand = models.ForeignKey(Brand, on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=120)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField(upload_to=image_folder)
    price = models.DecimalField(max_digits=9, decimal_places=0)
    available = models.BooleanField(default=True)
    objects = ProductManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('product_detail', kwargs={'product_slug': self.slug})


class CartItem(models.Model):

    product = models.ForeignKey(Product, on_delete=models.DO_NOTHING)
    qty = models.PositiveIntegerField(default=1)
    item_total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)

    def __str__(self):
        return "Cart item for product {0}".format(self.product.title)


class Cart(models.Model):

    items = models.ManyToManyField(CartItem, blank=True)
    cart_total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)

    def __str__(self):
        return str(self.id)

    def add_to_cart(self, product_slug):
        cart = self
        product = Product.objects.get(slug=product_slug)
        new_item, _ = CartItem.objects.get_or_create(product=product, item_total=product.price)
        if new_item not in cart.items.all():
            cart.items.add(new_item)
            cart.save()
        return

    def remove_from_cart(self, product_slug):
        cart = self
        product = Product.objects.get(slug=product_slug)
        for cart_item in cart.items.all():
            if cart_item.product == product:
                cart.items.remove(cart_item)
                cart.save()
        return

    def change_qty(self, qty, item_id):
        cart = self
        cart_item = CartItem.objects.get(id=int(item_id))
        cart_item.qty = int(qty)
        cart_item.item_total = int(qty) * Decimal(cart_item.product.price)
        cart_item.save()
        new_cart_total = 0.00
        for item in cart.items.all():
            new_cart_total += float(item.item_total)
        cart.cart_total = new_cart_total
        cart.save()

ORDER_STATUS_CHOICES = (
    ("Accepted for processing", "Accepted for processing"),
    ("Processing", "Processing"),
    ("Processed","Processed")
)

class Order(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING)
    items = models.ManyToManyField(Cart)
    total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    phone = models.CharField(max_length=20)
    address = models.CharField(max_length=255)
    buying_type = models.CharField(max_length=40, choices=(("Pick up from store", "Pick up from store"), 
        ("Delivery", "Delivery")), default="Pick up from store")
    date = models.DateTimeField(auto_now_add=True)
    comments = models.TextField()
    status = models.CharField(max_length=100, choices=ORDER_STATUS_CHOICES, default=ORDER_STATUS_CHOICES[0][0])

    def __str__(self):
        return "Order #{0}".format(str(self.id))

ecomapp/views.py
from decimal import Decimal
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.contrib.auth import login, authenticate
from ecomapp.forms import OrderForm, RegistrationForm, LoginForm
from ecomapp.models import Category, Product, CartItem, Cart, Order
# Create your views here.


def base_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    categories = Category.objects.all()
    products = Product.objects.all()
    context = {
        'categories': categories,
        'products': products,
        'cart': cart,
    }
    return render(request, 'base.html', context)


def product_view(request, product_slug):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    product = Product.objects.get(slug=product_slug)
    categories = Category.objects.all()
    context = {
        'product': product,
        'categories': categories,
        'cart': cart,
    }
    return render(request, 'product.html', context)


def category_view(request, category_slug):
    category = Category.objects.get(slug=category_slug)
    products_of_category = Product.objects.filter(category=category)
    context = {
        'category': category,
        'products_of_category': products_of_category,
    }
    return render(request, 'category.html', context)


def cart_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    context = {
        'cart': cart
    }
    return render(request, 'cart.html', context)


def add_to_cart_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    product_slug = request.GET.get('product_slug')
    product = Product.objects.get(slug=product_slug)
    cart.add_to_cart(product.slug)
    new_cart_total = 0.00
    for item in cart.items.all():
        new_cart_total += float(item.item_total)
    cart.cart_total = new_cart_total
    cart.save()
    return JsonResponse(
        {'cart_total': cart.items.count(),
         'cart_total_price':cart.cart_total})


def remove_from_cart_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    product_slug = request.GET.get('product_slug')
    product = Product.objects.get(slug=product_slug)
    cart.remove_from_cart(product.slug)
    new_cart_total = 0.00
    for item in cart.items.all():
        new_cart_total += float(item.item_total)
    cart.cart_total = new_cart_total
    cart.save()
    return JsonResponse(
        {'cart_total': cart.items.count(),
         'cart_total_price':cart.cart_total})


def change_item_qty(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    qty = request.GET.get('qty')
    item_id = request.GET.get('item_id')
    cart_item = CartItem.objects.get(id=int(item_id))
    cart.change_qty(qty, item_id)
    return JsonResponse(
        {'cart_total': cart.items.count(),
         'item_total': cart_item.item_total,
         'cart_total_price':cart.cart_total})


def checkout_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    context = {
        "cart": cart
    }
    return render(request, "checkout.html", context)


def order_create_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    form = OrderForm(request.POST or None)
    context = {
        "form": form
    }
    return render(request, 'order.html', context)


def make_order_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    form = OrderForm(request.POST or None)
    if form.is_valid():
        name = form.cleaned_data["name"]
        last_name = form.cleaned_data["last_name"]
        phone = form.cleaned_data["phone"]
        buying_type = form.cleaned_data["buying_type"]
        address = form.cleaned_data["address"]
        comments = form.cleaned_data["comments"]
        new_order = Order()
        new_order.user = request.user
        new_order.save()
        new_order.items.add(cart)
        new_order.first_name = name
        new_order.last_name = last_name
        new_order.phone = phone
        new_order.address = address
        new_order.buying_type = buying_type
        new_order.comments = comments
        new_order.total = cart.cart_total
        new_order.save()
        del request.session['cart_id']
        del request.session['total']
        return HttpResponseRedirect(reverse("thank_you"))


def account_view(request):
    order = Order.objects.filter(user=request.user).order_by('-id')
    context ={
        'order': order
    }
    return render(request, 'account.html', context)


def registration_view(request):
    form = RegistrationForm(request.POST or None)    
    if form.is_valid():
        new_user = form.save(commit=False)
        username = form.cleaned_data['username']        
        password = form.cleaned_data["password"]
        email = form.cleaned_data['email']
        first_name = form.cleaned_data['first_name']
        last_name = form.cleaned_data['last_name']
        new_user.username = username
        new_user.set_password(password)
        new_user.first_name = first_name
        new_user.last_name = last_name
        new_user.email = email
        new_user.save()
        login_user = authenticate(username=username, password=password)
        if login_user:
            login(request, login_user)
            return HttpResponseRedirect(reverse('base'))
    context ={
        'form': form
    }
    return render(request, 'registration.html', context)


def login_view(request):
    form = LoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data["username"]
        password = form.cleaned_data["password"]
        login_user = authenticate(username=username, password=password)
        if login_user:
            login(request, login_user)
            return HttpResponseRedirect(reverse('base'))
    context ={
        'form': form
    }
    return render(request, 'login.html', context)

ecomapp/templates/account.html
{% extends 'base.html' %}

{% block content %}

<h3 class='text-center'>Your orders, {{ request.user }}</h3>
<hr>

<table class='table'>
	 <tr style='background:lightblue;'>
	 	<td class="text-center">Order Number</td>
	 	<td class="text-center">Order Date</td>
	 	<td class="text-center">Order State</td>
	 	<td class="text-center">Order Price</td>
	 	<td class="text-center">Order Details</td>
	 	<td class="text-center"></td>
	 </tr>
	 {% for item in order %}
	 <tr>
	 	<td class="text-center" style='padding-top: 20px; padding-bottom: 10px;'>{{ item.id }}</td>
	 	<td class="text-center" style='padding-top: 20px; padding-bottom: 10px;'>{{ item.date }}</td>
	 	<td class="text-center" style='padding-top: 20px; padding-bottom: 10px;'>{{ item.status }}</td>
	 	<td class="text-center" style='padding-top: 20px; padding-bottom: 10px;'>{{ item.total }}</td>
	 	<td class="text-center" style='padding-top: 20px; padding-bottom: 10px;'></td>
	 </tr>

	 {% endfor %}
</table>

{% endblock content %}

ecomapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Shop Homepage - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link rel='stylesheet' href='{% static "css/bootstrap.css" %}'>

    <!-- Custom CSS -->
    <link rel='stylesheet' href='{% static "css/shop-homepage.css" %}'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">KupiSlona</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    {% if not request.get_full_path == '/' %}
                        <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                             aria-haspopup="true" aria-expanded="false">
                              Categories <span class="caret"></span></a>
                          <ul class="dropdown-menu">
                              {% for category in categories %}
                                <li><a href="{{ category.get_absolute_url }}">{{ category.name }}</a></li>
                              {% endfor %}
                          </ul>
                        </li>
                    {% endif %}
                    {% if not request.user.is_authenticated%}
                    <li>
                        <p class='navbar-text'>Welcome, guest</p>
                    </li>
                    <li>
                        <a href='{% url "login" %}'>Log In</a>
                    </li>
                    <li>
                        <a href='{% url "registration" %}'>Register</a>
                    </li>
                    {% else %}
                    <li>
                        <p class='navbar-text'>Welcome, {{ request.user }}</p>
                    </li>
                    <li>
                        <a href='{% url "account" %}'>Account details</a>
                    </li>
                    <li>
                        <a href='{% url "logout" %}'>Log Out</a>
                    </li>
                    {% endif %}
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href='{% url "cart" %}'>Your Cart <span class="badge" id='cart_count'>{% if not request.session.total %} 0 {% else %} {{ request.session.total }} {% endif %}</span></a></li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">
        {% block content %}
        <div class="row">
            <div class="col-md-3">
                <p class="lead">Elephants Of Your Dreams</p>
                <div class="list-group">
                	{% for category in categories %}
                        <a href="{{ category.get_absolute_url }}" class="list-group-item">{{ category.name }}</a>
                	{% endfor %}
                </div>
            </div>

            <div class="col-md-9">

                <div class="row carousel-holder">

                    <div class="col-md-12">
                        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                            <div class="carousel-inner">
                                {% for product in products %}
                                    {% if forloop.first %}
                                        <div class="item active">
                                            <img class="slide-image" src={{ product.image.url }} alt=""
                                                 style="padding-left: 300px; padding-right: 300px; height: 200px;">
                                            <br>
                                            <p class="text-center"><a href="{{ product.get_absolute_url }}">
                                                <button class="btn btn-info">{{ product.title }}</button></a></p>
                                        </div>
                                    {% else %}
                                        <div class="item">
                                            <img class="slide-image" src={{ product.image.url }} alt=""
                                                 style="padding-left: 300px; padding-right: 300px; height: 200px">
                                            <br>
                                            <p class="text-center"><a href="{{ product.get_absolute_url }}">
                                                <button class=" btn btn-info">{{ product.title }}</button></a></p>
                                        </div>
                                    {% endif %}
                                {% endfor %}
                            </div>
                            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev"
                               style="background: transparent">
                                <span class="glyphicon glyphicon-chevron-left" style="color: black;"></span>
                            </a>
                            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next"
                               style="background: transparent">
                                <span class="glyphicon glyphicon-chevron-right" style="color: black;"></span>
                            </a>
                        </div>
                    </div>

                </div>
                <br>
                <div class="row">
                    {% for product in products %}
                        <div class="col-sm-4 col-lg-4 col-md-4">
                            <div class="thumbnail">
                                <img src="{{ product.image.url }}" alt="" style='width:80%'>
                                <div class="caption">
                                    <h5><strong><a href="{{ product.get_absolute_url }}">{{ product.title }}
                                    </a></strong></h5>
                                    <h4 class="pull-down">{{ product.price }} $</h4>
                                    <p>{{ product.description }}</p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}

                </div>

            </div>
        </div>
        {% endblock content %}
    </div>
    <!-- /.container -->

    <div class="container">

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>&copy; Online Shop «KupiSlona™»</p>
                    <p>2019-2020</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src='{% static "js/jquery.js" %}'></script>

    <!-- Bootstrap Core JavaScript -->
    <script src='{% static "js/bootstrap.min.js" %}'></script>   

    <script>
        $(document).ready(function(){
            $('.add_to_cart').on('click', function(e)){
                e.preventDefault()
                product_slug = $(this).attr('data-slug')
                data={
                    product_slug: product_slug
                }
                $.ajax({
                    type: "GET",
                    url: '{% url "add_to_cart" %}',
                    data: data,
                    success: function(data){
                        $("#cart_count").html(data.cart_total)
                    }
                })
            }
        })
    </script> 
</body>

</html>

ecomapp/templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h2 class="text-center">Your Cart</h2>
    
{% if cart.items.count > 0 %}
<div class="my-cart">
<table class="table">
<tr>
    <td class="text-left"><strong>Product</strong></td>
    <td class="text-left"><strong>Amount</strong></td>
    <td class="text-left"><strong>Price</strong></td>
    <td class="text-left"></td>
</tr>
{% for item in cart.items.all %}
<tr class='cart-item-{{ item.product.id }}'>
    <td class="text-left">{{ item.product.title }}</td>
    <td class="text-left">
        <form action='' method='GET'>
            <input type='number' name='qty' class='cart-item-qty' data-id='{{ item.id }}'value='{{ item.qty }}' min='1' style='width: 65px;'>
        </form>
    </td>
    <td class="text-left" id='cart-item-total-{{ item.id }}'>{{ item.item_total }} $</td>
    <td class="text-left"><a href='#' class='remove_from_cart' data-slug='{{ item.product.slug }}' data-id='{{ item.product.id }}'><button class="btn btn-default">Remove from cart</button></a></td>
</tr>
{% endfor %}
<tr>
    <td></td>
    <td class="text-left"><strong>Total cost:</strong></td>
    <td class="text-left" id="cart-total-price"><strong>{{ cart.cart_total }} $</strong></td>
    <td class="text-left"></td>
</tr>
</table>
<br>
<a href='{% url "checkout" %}' class="pull-right"><button class="btn btn-info">View order</button></a>
</div>
<h3 class="cart-empty"></h3>
{% else %}
<br>
<h4 class="text-center">Itsa empty</h4>
{% endif %}
<script src='{% static "js/jquery.js" %}'></script>
<script>
$(document).ready(function(){
    $(".cart-empty").css("display", "none")
    $('.remove_from_cart').on('click', function(e){
        e.preventDefault()
        product_slug = $(this).attr('data-slug')        
        item_product_id = $(this).attr('data-id')    
        console.log(item_product_id)
        data = {
            product_slug: product_slug  
        }
        $.ajax({
            type: "GET",
            url: '{% url "remove_from_cart" %}',
            data: data,
            success: function(data){
                $("#cart_count").html(data.cart_total)
                $('.cart-item-'+item_product_id).css('display', 'none')
                $("#cart-total-price").html("<strong>" + parseFloat(data.cart_total_price).toFixed(2) + "$ </strong>")
                if(parseInt(data.cart_total) == 0){
                    $(".my-cart").css("display", "none")
                    $(".cart-empty").css("display", "block")
                    $(".cart-empty").html('<br><h4 class="text-center">Itsa empty</h4>')
                }
            }
        })
    })
})

$(document).ready(function(){
    $('.cart-item-qty').on('click', function(){
        qty = $(this).val()
        item_id = $(this).attr('data-id')
        data = {
            qty: qty,
            item_id: item_id
        }
        $.ajax({
            type: "GET",
            url: '{% url "change_item_qty" %}',
            data: data,
            success: function(data){
                $("#cart-item-total-"+item_id).html(parseFloat(data.item_total).toFixed(2) + "$")
                $("#cart-total-price").html("<strong>" + parseFloat(data.cart_total_price).toFixed(2) + "$ </strong>")
            }
        })
    })
})
</script>
{% endblock content %}

ecomapp/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="col-sm-12">
        <h2>{{ category.name }}</h2>
    <hr>
        {% for product in products_of_category %}
            <div class="col-sm-4">
                <img src="{{ product.image.url }}" style="width:100%">
                <h4 class="text-center">{{ product.title }}</h4>
                <p class="text-center" style="font-size: 20px">Price: <strong>{{ product.price }}$</strong></p>
                <p class="text-center"><a href="{{ product.get_absolute_url }}">
                                                <button class="btn btn-info">{{ product.title }}</button></a></p>
            </div>
        {% endfor %}
    </div>
    <script src='{% static "js/jquery.js" %}'></script>
    <script>
        $(document).ready(function(){
            $('.add_to_cart').on('click', function(e)){
                e.preventDefault()
                product_slug = $(this).attr('data-slug')
                data={
                    product_slug: product_slug
                }
                $.ajax({
                    type: "GET",
                    url: '{% url "add_to_cart" %}',
                    data: data,
                    success: function(data){
                        $("#cart_count").html(data.cart_total)
                    }
                })
            }
        })
    </script> 
{% endblock content %}

ecomapp/templates/checkout.html
{% extends 'base.html' %}

{% block content %}
<h3 class="text-center">Your Order</h3>
<br>
<table class="table">
<tr>
    <td class="text-left"><strong>Product</strong></td>
    <td class="text-left"><strong>Amount</strong></td>
    <td class="text-left"><strong>Price</strong></td>
    <td class="text-left"></td>
</tr>
{% for item in cart.items.all %}
<tr>
    <td class="text-left">{{ item.product.title }}</td>
    <td class="text-left">{{ item.qty }}</td>
    <td class="text-left">{{ item.item_total }} $</td>
    <td></td>
</tr>
{% endfor %}
<tr>
    <td></td>
    <td class="text-left"><strong>Total cost:</strong></td>
    <td class="text-left"><strong>{{ cart.cart_total }} $</strong></td>
    <td class="text-left"></td>
</tr>
</table>
<a href='{% url "create_order" %}' class="pull-right"><button class="btn btn-success">Place Order</button></a>
{%endblock content%}

ecomapp/templates/order.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<form action="{% url 'make_order' %}" method="POST">
{% csrf_token %}
<div class='col-sm-4'>
	{{ form.name|as_crispy_field }}
</div>
<div class='col-sm-4'>
	{{ form.last_name|as_crispy_field }}
</div>
<div class='col-sm-4'>
	{{ form.phone|as_crispy_field }}
</div>
{{ form.buying_type|as_crispy_field }}
{{ form.address|as_crispy_field }}
{{ form.date|as_crispy_field }}
{{ form.comments|as_crispy_field }}
<input type='submit' class='btn btn-success' value='Confirm'>
</form>	
<br>
<script src='{% static "js/jquery.js" %}'></script>
<script>
	$(document).ready(function(){
		$("#div_id_address").css("display", "none")
		$("#id_buying_type").on("click", function(){
			buying_type = $(this).val()
			if(buying_type == "delivery"){
				$("#div_id_address").css("display", "block")
			}else{
				$("#div_id_address").css("display", "none")
			}
		})
		$("#id_date_month").css("width", "100px")
		$("#id_date_month").css("display", "inline")
		$("#id_date_year").css("width", "100px")
		$("#id_date_year").css("display", "inline")
		$("#id_date_day").css("width", "70px")
		$("#id_date_day").css("display", "inline")
	})
</script>
{%endblock content%}